# Generated by Django 4.2.28 on 2026-02-15 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_categor_a61a21_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider'], name='services_provide_54febe_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'category'], name='services_is_acti_bfb1a7_idx'),
        ),
    ]
